# name: ci
# on:
#   pull_request:
#     paths:
#       - 'src/**'
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]
#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     # - run: npm ci
#     # - run: npm run build --if-present
#     # - run: npm test


name: Batman

on:
  pull_request_review_comment:
    types:
     - created

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        method: squash
        delete_source_branch: true